
INSERT INTO professors (departmentid, name) VALUES 
(1, 'Ruf, Christopher'), 
(1, 'Tewari, Ambuj'), 
(1, 'Eustice, Ryan'), 
(1, 'Neuhoff, David'), 
(1, 'Daniszewski, David'), 
(1, 'Schotland, John'), 
(1, 'Kieras, David'), 
(1, 'Finelli, Cindy'), 
(1, 'Newman, Mark'), 
(1, 'Volkovich, Ilya'), 
(1, 'Jamin, Sugih'), 
(1, 'Bertacco, Valeria'), 
(1, 'Berman, Paul'), 
(1, 'Kim, Hun'), 
(1, 'Foster, John'), 
(1, 'Brehob, Mark'), 
(1, 'Renno, Nilton'), 
(1, 'Hofmann, Heath'), 
(1, 'Lee, Somin'), 
(1, 'Cain, Charles'), 
(1, 'Lukefahr, Andrew'), 
(1, 'Xu, Zhen'), 
(1, 'Blaauw, David'), 
(1, 'Prakash, Atul'), 
(1, 'Sakallah, Karem'), 
(1, 'Mei, Qiaozhu'), 
(1, 'Peterson, Becky'), 
(1, 'Schoenebeck, Grant'), 
(1, 'Oldham, Kenn'), 
(1, 'Shin, Kang'), 
(1, 'Zou, Shasha'), 
(1, 'Mihalcea, Rada'), 
(1, 'Vasudevan, Ram'), 
(1, 'Shirani Chaharsooghi, Farhad'), 
(1, 'Van Hentenryck, Pascal'), 
(1, 'Stout, Quentin'), 
(1, 'Wellman, Michael'), 
(1, 'Chesney, David'), 
(1, 'Zhong, Zhaohui'), 
(1, 'Lu, Wei'), 
(1, 'Zhang, Zhengya'), 
(1, 'Fan, Xudong'), 
(1, 'Grizzle, Jessy'), 
(1, 'Jarrahi, Mona'), 
(1, 'Goldman, Rachel'), 
(1, 'Garcia-Ramirez, Hector'), 
(1, 'Abney, Steven'), 
(1, 'Collins-Thompson, Kevyn'), 
(1, 'Noll, Douglas'), 
(1, 'Radev, Dragomir'), 
(1, 'Darden, Marcus'), 
(1, 'Papaefthymiou, Marios'), 
(1, 'Lahiji, Gholamhassan'), 
(1, 'Claflin, Dennis'), 
(1, 'Polk, Thad'), 
(1, 'Mars, Jason'), 
(1, 'Guo, L'), 
(1, 'Hayes, John'), 
(1, 'Atkins III, Daniel'), 
(1, 'Winful, Herbert'), 
(1, 'Narayanasamy, Satish'), 
(1, 'Anastasopoulos, Achilleas'), 
(1, 'Rand, Stephen'), 
(1, 'Mower Provost, Emily'), 
(1, 'Deng, Jia'), 
(1, 'Ramani, Sathish'), 
(1, 'Pollack, Martha'), 
(1, 'Lafortune, Stephane'), 
(1, 'Juett, James'), 
(1, 'Jagadish, Hosagrahar'), 
(1, 'Fu, Kevin'), 
(1, 'Gianchandani, Yogesh'), 
(1, 'Mi, Zetian'), 
(1, 'Savarese, Silvio'), 
(1, 'Ku, Pei-Cheng'), 
(1, 'Kurabayashi, Katsuo'), 
(1, 'Das, Reetuparna'), 
(1, 'Revzen, Shai'), 
(1, 'Compton, Kevin'), 
(1, 'Norris, Theodore'), 
(1, 'Kanicki, Jerzy'), 
(1, 'Mahlke, Scott'), 
(1, 'Tang, Lingjia'), 
(1, 'Kim, Boklye'), 
(1, 'Chen, Peter'), 
(1, 'Durfee, Edmund'), 
(1, 'Arthur, William'), 
(1, 'Dutta, Prabal'), 
(1, 'Najarian, Kayvan'), 
(1, 'Hiskens, Ian'), 
(1, 'Mathieu, Johanna'), 
(1, 'Atkins, Ella'), 
(1, 'Galvanauskas, Almantas'), 
(1, 'Wiens, Jenna'), 
(1, 'Flynn, Michael'), 
(1, 'Mahdavifar, Hessam'), 
(1, 'Ozay, Necmiye'), 
(1, 'Honeyman, Peter'), 
(1, 'England, Anthony'), 
(1, 'Phillips, Jamie'), 
(1, 'Chandrahalim, Hengky'), 
(1, 'Morgan, Andrew'), 
(1, 'Abernethy, Jacob'), 
(1, 'Afshari, Ehsan'), 
(1, 'Subramanian, Vijay'), 
(1, 'Rivas Davila, Juan'), 
(1, 'Cafarella, Michael'), 
(1, 'Winick, Kim'), 
(1, 'Sarabandi, Kamal'), 
(1, 'Kaplan, Stephen'), 
(1, 'Stefanopoulou, Anna'), 
(1, 'Newstadt, Gregory'), 
(1, 'Dorf, Mary'), 
(1, 'Kamil, Amir'), 
(1, 'Wakefield, Gregory'), 
(1, 'Islam, Mohammed'), 
(1, 'Ye, Jieping'), 
(1, 'Deotare, Parag'), 
(1, 'Austin, Todd'), 
(1, 'Gilbert, Anna'), 
(1, 'Meerkov, Semyon'), 
(1, 'Kuipers, Benjamin'), 
(1, 'Laird, John'), 
(1, 'Zhang, Jun'), 
(1, 'Peikert, Christopher'), 
(1, 'Liu, Mingyan'), 
(1, 'Pipe, Kevin'), 
(1, 'Bond, Jeremy'), 
(1, 'McBride, Ryan'), 
(1, 'Willingale, Louise'), 
(1, 'Fessler, Jeffrey'), 
(1, 'Graetz, Emily'), 
(1, 'Balzano, Laura'), 
(1, 'Lasecki, Walter'), 
(1, 'Kapritsos, Manos'), 
(1, 'Kira, Mackillo'), 
(1, 'Terry Jr, Fred'), 
(1, 'Berenson, Dmitry'), 
(1, 'Yagle, Andrew'), 
(1, 'Forrest, Stephen'), 
(1, 'Tilbury, Dawn'), 
(1, 'Ferrer Minguez, Gonzalo'), 
(1, 'Mudge, Trevor'), 
(1, 'Tsang, Leung'), 
(1, 'Essl, Georg'), 
(1, 'Lynch, Jerome'), 
(1, 'Gilchrist, Brian'), 
(1, 'Ganago, Alexander'), 
(1, 'Thomason, Richmond'), 
(1, 'Flinn, Jason'), 
(1, 'Mozafari, Barzan'), 
(1, 'Bruns, Timothy'), 
(1, 'Noble, Brian'), 
(1, 'Girard, Anouck'), 
(1, 'Ahaus, Raymond'), 
(1, 'Singh, Jasprit'), 
(1, 'Kipke, Daryl'), 
(1, 'Wentzloff, David'), 
(1, 'Sun, Jing'), 
(1, 'Soloway, Elliot'), 
(1, 'Mao, Z'), 
(1, 'Avestruz, Al-Thaddeus'), 
(1, 'Madhyastha, Harsha'), 
(1, 'DeOrio, Andrew'), 
(1, 'Strauss, Martin'), 
(1, 'Paoletti, David'), 
(1, 'Corso, Jason'), 
(1, 'Adar, Eytan'), 
(1, 'Hero III, Alfred'), 
(1, 'Slavin, James'), 
(1, 'Oney, Steve'), 
(1, 'Rais-Zadeh, Mina'), 
(1, 'Teneketzis, Demosthenis'), 
(1, 'Stark, Wayne'), 
(1, 'Chowdhury, N'), 
(1, 'Shi, Yaoyun'), 
(1, 'Najafi, Khalil'), 
(1, 'Merlin, Roberto'), 
(1, 'Ackerman, Mark'), 
(1, 'Jenkins, Odest'), 
(1, 'Syed, Zeeshan'), 
(1, 'Markov, Igor'), 
(1, 'Kushner, Mark'), 
(1, 'Bernstein, Dennis'), 
(1, 'Holland, John'), 
(1, 'Lee, Honglak'), 
(1, 'Baveja, Satinder'), 
(1, 'Dick, Robert'), 
(1, 'Freudenberg, James'), 
(1, 'Koutra, Danai'), 
(1, 'Grbic, Anthony'), 
(1, 'Sylvester, Dennis'), 
(1, 'Olson, Edwin'), 
(1, 'Scott, Clayton'), 
(1, 'Kay, Matthew'), 
(1, 'Johnson-Roberson, Matthew'), 
(1, 'Lefevre, Kristen'), 
(1, 'Steel, Duncan'), 
(1, 'Nadakuditi, Raj'), 
(1, 'Carmon, Tal'), 
(1, 'Pradhan, S'), 
(1, 'Ringenberg, Jeff'), 
(1, 'Halderman, J'), 
(1, 'Jahanian, Farnam'), 
(1, 'Mortazawi, Amir'), 
(1, 'Munson Jr, David'), 
(1, 'Wenisch, Thomas'), 
(1, 'Mazumder, Pinaki'), 
(1, 'Lady, Kyle'), 
(1, 'Gillespie, Brent'), 
(1, 'Scruggs, Jeffrey'), 
(1, 'Dreslinski Jr, Ronald'), 
(1, 'Yoon, Euisik'), 
(1, 'Cook, Jeffrey'), 
(1, 'Hicks, Matthew'), 
(1, 'Pettie, Seth'), 
(1, 'Bhattacharya, Pallab'), 
(1, 'Ulaby, Fawwaz'), 
(1, 'Michielssen, Eric'), 
(1, 'Kabamba, Pierre'), 
(1, 'Marsman, Eric');

INSERT INTO courses (departmentid, number, title) VALUES 
(1, 101, 'Thriving in a Digital World'), 
(1, 183, 'Elementary Programming Concepts'), 
(1, 203, 'Discrete Math'), 
(1, 215, 'Introduction to Electronic Circuits'), 
(1, 216, 'Introduction to Signals and Systems'), 
(1, 230, 'Electromagnetics I'), 
(1, 250, 'Elec Sens Sys'), 
(1, 270, 'Introduction to Logic Design'), 
(1, 280, 'Programming and Introductory Data Structures'), 
(1, 281, 'Data Structures and Algorithms'), 
(1, 282, 'Information Systems Design and Programming'), 
(1, 283, 'Prog for Sci&amp;Eng'), 
(1, 285, 'A Programming Language or Computer System'), 
(1, 301, 'Probabilistic Methods in Engineering'), 
(1, 311, 'Analog Circuits'), 
(1, 312, 'Digital Integrated Circuits'), 
(1, 314, 'Electrical Circuits, Systems and Applications'), 
(1, 320, 'Introduction to Semiconductor Devices'), 
(1, 330, 'Introduction to Antennas and Wireless Systems'), 
(1, 334, 'Principles of Optics'), 
(1, 351, 'Introduction to Digital Signal Processing'), 
(1, 353, 'Intro Comm Systems'), 
(1, 370, 'Introduction to Computer Organization'), 
(1, 373, 'Design of Microprocessor Based Systems'), 
(1, 376, 'Foundations of Computer Science'), 
(1, 381, 'Object Oriented and Advanced Programming'), 
(1, 382, 'Internet-Scal Comp'), 
(1, 388, 'Introduction to Computer Security'), 
(1, 398, 'Special Topics'), 
(1, 399, 'Directed Study'), 
(1, 402, 'Computer Programming For Scientists and Engineers'), 
(1, 406, 'High-Tech Entrep'), 
(1, 410, 'Patent Fund Eng'), 
(1, 411, 'Microwave Circuits I'), 
(1, 413, 'Monolith Amplifier Circuits'), 
(1, 416, 'Elec for Bio'), 
(1, 417, 'Electrical Biophysics'), 
(1, 418, 'Power Electronics'), 
(1, 419, 'Elec Mach and Drives'), 
(1, 421, 'Properties of Transistors'), 
(1, 423, 'Solid-State Device Laboratory'), 
(1, 425, 'Integrated Microsystems Laboratory'), 
(1, 427, 'Very Large Scale Integrated Design I'), 
(1, 429, 'Semi Optoelec Dev'), 
(1, 430, 'Radiowave Prop'), 
(1, 434, 'Princ of Photonics'), 
(1, 435, 'Fourier Optics'), 
(1, 438, 'Adv Lasers Lab'), 
(1, 441, 'Mobile App Development for Entrepreneurs'), 
(1, 442, 'Computer Vision'), 
(1, 443, 'Senior ThesisL'), 
(1, 445, 'Introduction to Machine Learning'), 
(1, 452, 'Digital Signal Processing Design Laboratory'), 
(1, 453, 'Applied Matrix Algorithms for Signal Processing, Data Analysis, and Machine Learning'), 
(1, 455, 'Digital Communication Signals and Systems'), 
(1, 458, 'Biomedical Instrumentation and Design'), 
(1, 460, 'Control Systems Analysis and Design'), 
(1, 461, 'Embedded Control Systems'), 
(1, 463, 'Power Systems Design and Operations'), 
(1, 464, 'Hands-on Robotics'), 
(1, 467, 'Autonomous Robotics'), 
(1, 470, 'Computer Architecture'), 
(1, 473, 'Advanced Embedded Systems'), 
(1, 475, 'Introduction to Cryptography'), 
(1, 477, 'Introduction to  Algorithms'), 
(1, 478, 'Logic Circuit Synthesis and Optimization'), 
(1, 480, 'Logic Formal Verif'), 
(1, 481, 'Software Engineering'), 
(1, 482, 'Introduction to Operating Systems'), 
(1, 483, 'Compiler Construction'), 
(1, 484, 'Database Management Systems'), 
(1, 485, 'Web Database and Information Systems'), 
(1, 486, 'Informational Retrieval and Web Search'), 
(1, 487, 'Interactive Computer Graphics'), 
(1, 489, 'Comp Networks'), 
(1, 490, 'Programming Languages'), 
(1, 492, 'Introduction to Artificial Intelligence'), 
(1, 493, 'User Interface Development'), 
(1, 494, 'Computer Game Design and Development'), 
(1, 496, 'Major Design Experience-Professionalism'), 
(1, 497, 'Major Des Projects'), 
(1, 498, 'Special Topics'), 
(1, 499, 'Adv Directed Study'), 
(1, 500, 'Tutorl Sys Sci'), 
(1, 501, 'Probability and Random Processes'), 
(1, 502, 'Stochastic Processes'), 
(1, 503, 'Intro Numerical Em'), 
(1, 504, 'Foundations of Computer Vision'), 
(1, 509, 'BIOMEMS'), 
(1, 510, 'RF MEMS'), 
(1, 511, 'A/D Interfaces'), 
(1, 512, 'Amorphous Sem Dev'), 
(1, 513, 'Flat Pan Displays'), 
(1, 514, 'Advanced MEMS'), 
(1, 515, 'Integrated Microsystems'), 
(1, 516, 'Medical Imaging System'), 
(1, 517, 'Proc Plasma'), 
(1, 518, 'Magnetosphere'), 
(1, 519, 'Plasma Lab'), 
(1, 520, 'Solid State Physics'), 
(1, 521, 'Solid State Devices'), 
(1, 522, 'Analog Integr Ckts'), 
(1, 525, 'Adv Sol St Mw Cir'), 
(1, 526, 'Plasmonics'), 
(1, 527, 'Layout Synthesis&amp;Opt'), 
(1, 528, 'M-Elec Proc Tech'), 
(1, 529, 'Semi Lasers &amp; Leds'), 
(1, 530, 'Electromagnetic Theory I'), 
(1, 531, 'Antenna Thry&amp;Des'), 
(1, 532, 'M-Waves Rem Sens'), 
(1, 533, 'Micro Meas Lab'), 
(1, 535, 'Optical Inform Proc'), 
(1, 536, 'Statistical Optics'), 
(1, 537, 'Classical Optics'), 
(1, 538, 'Optical Waves in Crystals'), 
(1, 539, 'Lasers'), 
(1, 540, 'Applied Quantum Mechanics'), 
(1, 541, 'App Qnt Mch II'), 
(1, 542, 'Advanced Topics in Computer Vision'), 
(1, 543, 'Knowledge-Based Systems'), 
(1, 545, 'Machine Learning'), 
(1, 546, 'Ultrafast Optics'), 
(1, 547, 'Electronic Commerce'), 
(1, 548, 'Information Visualization'), 
(1, 549, 'Information Retrieval'), 
(1, 550, 'Information Theory'), 
(1, 551, 'Matrix Methods for Signal Processing, Data Analysis and Machine Learning'), 
(1, 552, 'Fib Opt:Intrnt Biomd'), 
(1, 553, 'Data Compression'), 
(1, 554, 'Introduction to Digital Communication and Coding'), 
(1, 555, 'Digital Commun Thry'), 
(1, 556, 'Image Processing'), 
(1, 557, 'Communication Netwk'), 
(1, 558, 'Stochastic Control'), 
(1, 559, 'Adv Signal Process'), 
(1, 560, 'Linear Systems Theory'), 
(1, 561, 'Design of Digital Control Systems'), 
(1, 562, 'Nonlinear Systems and Control'), 
(1, 564, 'Estimation, Filtering, and Detection'), 
(1, 565, 'Linear Feedback Control Systems'), 
(1, 566, 'Discrete Event Syst'), 
(1, 567, 'Robot Kinematics and Dynamics'), 
(1, 568, 'Mobile Robotics: Methods and Algorithms'), 
(1, 569, 'Prod Syst Eng'), 
(1, 570, 'Parallel Computer Architecture'), 
(1, 571, 'Principles of Real Time Computing'), 
(1, 573, 'Microarchitecture'), 
(1, 574, 'Computational Complexity'), 
(1, 575, 'Advanced Cryptography'), 
(1, 578, 'Correct Operation for Processors and Embedded Systems'), 
(1, 579, 'Digital System Testing'), 
(1, 580, 'Adv Comp Graphics'), 
(1, 581, 'Soft Eng Tool'), 
(1, 582, 'Adv Operat Sys'), 
(1, 583, 'Advanced Compilers'), 
(1, 584, 'Advanced Database Systems'), 
(1, 586, 'Design and Analysis of Algorithms'), 
(1, 587, 'Parallel Computing'), 
(1, 588, 'Comp Netwk Security'), 
(1, 589, 'Advanced Computer Networks'), 
(1, 590, 'Advanced Programming Languages'), 
(1, 591, 'Distribute Sys'), 
(1, 592, 'Foundations of Artificial Intelligence'), 
(1, 593, 'Hum as Inf Proc'), 
(1, 594, 'Intro Adaptive Syst'), 
(1, 595, 'Natural Language Processing'), 
(1, 596, 'M Eng Team Project'), 
(1, 597, 'Language &amp; Info'), 
(1, 598, 'Special Topics in Electrical Engineering and Computer Science'), 
(1, 599, 'Directed Study'), 
(1, 600, 'Func Meth Sys Thry'), 
(1, 620, 'Elect Opt Semicon'), 
(1, 627, 'VLSI Design II'), 
(1, 628, 'Adv Hi Perf VLSI'), 
(1, 631, 'Em Scattering'), 
(1, 633, 'Num Meth E-M'), 
(1, 634, 'Nonlin Opt'), 
(1, 638, 'Quantum Opt'), 
(1, 643, 'Theory of Neural Computation'), 
(1, 644, 'Comp Model Cogn'), 
(1, 650, 'Chanel Coding Thry'), 
(1, 659, 'Adapt Signal Proc'), 
(1, 662, 'Adv Nl Cont'), 
(1, 670, 'Spec Top Comp Arch'), 
(1, 674, 'Spec Tpc Theor CmpSc'), 
(1, 682, 'Software Sys Topics'), 
(1, 684, 'Curr Top Database'), 
(1, 691, 'Mobile Computing'), 
(1, 692, 'Adv Artif Intellig'), 
(1, 695, 'Neural Models'), 
(1, 698, 'Master&#39;s Thesis'), 
(1, 699, 'Research Work EECS'), 
(1, 700, 'Spec Topic Sys Thry'), 
(1, 720, 'Topics S-State Dev'), 
(1, 730, 'Topic Electromagnet'), 
(1, 735, 'Topic Optical Sci'), 
(1, 750, 'Topic Comm&amp;Inf Thry'), 
(1, 755, 'Topics Signal Proc'), 
(1, 760, 'Topic Control Thry'), 
(1, 765, 'Sp T Stoch Sys Cont'), 
(1, 767, 'Adv Nat Lang Pro Inf'), 
(1, 770, 'Topic Computer Sys'), 
(1, 792, 'Spec Top Artif Intel'), 
(1, 820, 'Sem in S-S Elec'), 
(1, 892, 'Sem Art Intelligenc'), 
(1, 990, 'Diss-Precand'), 
(1, 995, 'Diss-Cand');
